[main]
file_path = "default.xex"
out_directory_path = "recomp"
switch_table_file_path = "jump.toml"
# patch_file_path = "default.xexp"
# patched_file_path = "patched.xex"

restgprlr_14_address = 0x82fa7690
savegprlr_14_address = 0x82fa7640
restfpr_14_address = 0x82fa8d3c
savefpr_14_address = 0x82fa8cf0
restvmx_14_address = 0x82fac178
savevmx_14_address = 0x82fabee0
restvmx_64_address = 0x82fac20c
savevmx_64_address = 0x82fabf74

# Optional settings
skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

functions = [
    { address = 0x822c1c98, size = 0x30 },
    { address = 0x82424128, size = 0xFFF34 },
    { address = 0x82325980, size = 0x15C }
]
